package PP;

import java.awt.Desktop;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Orlando
 */
public class ZonaDeTrabajo extends javax.swing.JFrame 
{
    String name;
    public ZonaDeTrabajo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CrearRepo = new javax.swing.JButton();
        VerRepo = new javax.swing.JButton();
        EditarRepo = new javax.swing.JButton();
        About = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Work Zone");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Bienvenido a la Zona de Trabajo:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("¿Qué acción deseas realizar?");

        CrearRepo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CrearRepo.setText("Crear Repositorio");
        CrearRepo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearRepoMouseClicked(evt);
            }
        });
        CrearRepo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearRepoActionPerformed(evt);
            }
        });

        VerRepo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        VerRepo.setText("Ver Repositorios");
        VerRepo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerRepoActionPerformed(evt);
            }
        });

        EditarRepo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EditarRepo.setText("Editar Repositorios");
        EditarRepo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarRepoActionPerformed(evt);
            }
        });

        About.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        About.setText("Acerca de...");
        About.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CrearRepo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(VerRepo))
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EditarRepo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(About, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(About))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CrearRepo)
                    .addComponent(VerRepo)
                    .addComponent(EditarRepo))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrearRepoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearRepoActionPerformed
        Path path = Paths.get("C:\\Users\\Orlando\\Documents\\NetBeansProjects\\PP\\Repositorios");
        name = JOptionPane.showInputDialog("Dime el nombre de tu Repositorio: ");
        File folder = new File(name);
        folder.mkdir();
        JOptionPane.showMessageDialog(null,"Â¡Â¡Â¡Repositorio creado con exito :D!!!",null,JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_CrearRepoActionPerformed

    private void CrearRepoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearRepoMouseClicked
        


    }//GEN-LAST:event_CrearRepoMouseClicked

    private void VerRepoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerRepoActionPerformed
        String sDirectorio = "C:\\Users\\Orlando\\Documents\\NetBeansProjects\\PP\\Repositorios";
        File f = new File(sDirectorio);
        if (f.exists())
        {
            JOptionPane.showMessageDialog(null,"El archivo existe.");
            File[] ficheros = f.listFiles();
            for (File fichero : ficheros) 
            {
            //System.out.println(fichero.getName());
            JOptionPane.showMessageDialog(null,fichero.getName(),null,JOptionPane.INFORMATION_MESSAGE);
            }
        }
        else {}
        
    }//GEN-LAST:event_VerRepoActionPerformed

    private void EditarRepoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarRepoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditarRepoActionPerformed

    private void AboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutActionPerformed
        abrirArchivo("AcercaDe.txt");
    }//GEN-LAST:event_AboutActionPerformed

    public void abrirArchivo(String archivo)
    {

     try 
     {
            File objetofile = new File ("AcercaDe.txt");
            Desktop.getDesktop().open(objetofile);
     }catch (IOException ex) 
     {
            System.out.println(ex);
     }

    }                         

    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ZonaDeTrabajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ZonaDeTrabajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ZonaDeTrabajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ZonaDeTrabajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ZonaDeTrabajo().setVisible(true);
            }
        });
        //System.exit(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton About;
    private javax.swing.JButton CrearRepo;
    private javax.swing.JButton EditarRepo;
    private javax.swing.JButton VerRepo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}